BASE_URL = 'https://bandcamp.com/'
TAGS = 'tag/'
DIG_DEEPER = 'https://bandcamp.com/api/hub/2/dig_deeper'

BODY = '{"filters":{"format":"all","location":0,"sort":"pop",'

ALBUM_SELECTOR = 'li.music-grid-item > a[href]'
TRACK_SELECTOR = 'tr.track_row_view > td.title-col > div.title > a[href]'
ALBUM_NAME_SELECTOR = 'div#name-section > h2.trackTitle'

[HEADERS]
    User-Agent = 'Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0'
    Accept = '*/*'
    Accept-Language = 'en-GB,en;q=0.5'
    Content-Type = 'application/x-www-form-urlencoded'
    X-Requested-With = 'XMLHttpRequest'
